### ISSUE TITLE
Please update it with new version of kreait/firebase-php

### ISSUE THREAD

**Issue by cskushwah** [grptx/yii2-firebase#1]
Hi,
I want to use the FCM message but not able to use it. which is implemented in kreait/firebase-php : ^4.0.
Please update it with new updated version for kreait/firebase-php.   

I had try to update firebase-php with 'composer update  grptx/yii2-firebase' command but not get any success.
if i can update it with new version then please help me.

**Comment by grptx** [comment]
I published a new release (0.4) with kreait/firebase-php to version 4
but it's not well tested yet
install it using "grptx/yii2-firebase":"^4"

**Comment by cskushwah** [comment]
Thank you so much @grptx
